
# yaml-language-server: $schema=https://security-api.appsec.inday.io/schemas/security_config.json
# This is the configuration file for Chimera. This file is required to allow scanning platform to scan your repo.
# Please see https://confluence.workday.com/pages/viewpage.action?pageId=1943985516

#####################
# CHANGE LOG
#####################
# Webhook install date : 2024-02-09 13:48:27
# User addtion date : 2024-02-09 13:48:27

#####################
# SLACK CONFIGURATION
#####################
# Uncomment the below section and provide a Slack channel's name to allow Chimera to
# notifiy your slack channel about scans. Please see Chimera documentation on how to do this.
# slack:
  # enabled: true
  # channel: 

##########################
# SCAN TOOL  CONFIGURATION
##########################

tools_config:
  semgrep:
    rulesets:
    - p/python
  snyk: {}
  trufflehog: {}
